#include "iostream"

using namespace std;
/*
problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


int main()
{
    int sum = 0;
    int fibLesser = 1;
    int fibGreater = 2;
    int tempSwap;
    while (fibGreater < 4000000)
    {
        if(fibGreater%2==0)
            sum += fibGreater;
            
        tempSwap = fibGreater;
        fibGreater = fibLesser + fibGreater;
        fibLesser = tempSwap;
        
    }
   cout << sum << endl; 
   
   return 0;
}
